django_proyecto/urls.py
from django.contrib import admin
from django.urls import path
from app_proyecto import views

urlpatterns = [
    path('admin/', admin.site.urls), #Administraciòn por defecto

    #LINKS DE SESIÓN
    path('login/', views.login, name = 'login'), #Iniciar sesiòn
    path('salir/', views.logout, name = 'salir'),

    #LINKS DEL GERENTE
    path('inicio_gerente/', views.inicio_gerente, name = 'inicio_gerente'),
    path('consulta_empleados/', views.consulta_empleados.as_view(), name = 'consulta_empleados'),
    path('consulta_supervisores/', views.consulta_supervisores.as_view(), name = 'consulta_supervisores'),
    path('consulta_gerentes/', views.consulta_gerentes.as_view(), name = 'consulta_gerentes'),

#FORMULARIO
   # 1.- Crear a la persona
	path('form_persona/', views.form_persona.as_view(), name = 'form_persona'),
	path('form_persona_domicilio/', views.form_persona_domicilio.as_view(), name = 'form_persona_domicilio'),

    #2.- Json
    path("json_supervisor/", views.json_supervisor),


    #Examenes
    path('examen_jefe_abarrotes/', views.examen_jefe_abarrotes, name = 'examen_jefe_abarrotes'),
    path('examen_cajas/', views.examen_cajas, name = 'examen_cajas'),
]

app_proyecto/models.py
from django.db import models
import datetime

# Create your models here.
class PuestoEmpleado(models.Model):
	Id_Puesto = models.CharField(max_length = 40, primary_key = True)

	def __str__(self):
		return  str(self.Id_Puesto)

class Personas(models.Model):
	Curp = models.CharField(max_length = 20, primary_key = True)
	Nombres = models.CharField(max_length = 150)
	Ap_Paterno = models.CharField(max_length = 100)
	Ap_Materno = models.CharField(max_length = 100)
	NSS = models.CharField(max_length = 40) 
	RFC = models.CharField(max_length = 40) 
	Fecha_Nacimiento = models.DateField(auto_now=False, auto_now_add=False)
	Edo_Civil = (
        ("Casado", 'Casado'),
        ("Soltero", 'Soltero'),
        ("Divorciado", 'Divorciado'),
        ("Viudo", 'Viudo'),
        ("Comprometido", 'Comprometido'),
    )
	Escolaridad = (
        ("Primaria",'Primaria'),
        ("Secundaria",'Secundaria'),
        ("Preparatoria",'Preparatoria'),
        ("Universidad",'Universidad'),
    )

	estado_civil=models.CharField(choices=Edo_Civil,max_length=50)
	nivel_escolar = models.CharField(max_length=50, choices=Escolaridad)

	def __str__(self):
		return  self.Curp

class DireccionPersonas(models.Model):
	Curp = models.ForeignKey(Personas, on_delete=models.CASCADE)
	Calle = models.CharField(max_length = 200)
	Colonia = models.CharField(max_length = 200)
	Num_Interior = models.CharField(max_length = 30)
	Num_Exterior = models.CharField(max_length = 30)

	def __str__(self):
		return  self.Curp.Curp

class Empleado(models.Model):
	No_Empleado = models.AutoField(primary_key=True) #autoincrementable
	Curp = models.ForeignKey(Personas, on_delete=models.CASCADE)
	Id_Puesto = models.ForeignKey(PuestoEmpleado, on_delete=models.CASCADE)
	contraseña = models.CharField(max_length=50)
	estado = models.BooleanField(default=True)
	def __str__(self):
		return self.Curp.Curp + ", \t" + str(self.Id_Puesto)

class AreasTrabajo(models.Model):
	Id_Area = models.CharField(max_length = 20, primary_key = True)
	Nombre = models.CharField(max_length = 150)
	Encargado = models.ForeignKey(Empleado, on_delete=models.CASCADE)

	def __str__(self):
		return  self.Nombre

class Examen(models.Model):
	Id_Examen = models.CharField(max_length = 50, primary_key=True)
	Nombre = models.CharField(max_length = 150)
	Id_Area = models.ForeignKey(AreasTrabajo, on_delete=models.CASCADE)
	puntaje_minimo = models.IntegerField()
	puntaje_maximo = models.IntegerField()

	def __str__(self):
		return  self.Nombre

class ExamenPersonas(models.Model):
	Num_Examen = models.AutoField(primary_key=True) #autoincrementable
	Curp = models.ForeignKey(Personas, on_delete=models.CASCADE)
	Id_Examen = models.ForeignKey(Examen, on_delete=models.CASCADE)
	Fecha_Elaborado = models.DateField(auto_now=True)

	def __str__(self):
		return  str(self.Num_Examen) + ", Curp: " + str(self.Curp.Curp)

class ResultadoExamenes(models.Model):
	Num_Examen = models.ForeignKey(ExamenPersonas, on_delete=models.CASCADE)
	Puntaje = models.IntegerField()
	Dictamen=models.CharField(max_length=50)

	def __str__(self):
		return str(self.Num_Examen)


# Enrutamiento estatico: con este enrutamiento el enrutador es ordenado por el administrador de la red, 
# por deonde llegan las redes remotes, se configura manualmente y dentro de sus ventajas, está el control
# total sobre la seleccion de la ruta. 
# 	Ventajas: 
# 		Disponibilidad

# Enrutamiento dinamico: se logra mediante el uso de los protocolos de enrutamiento RIP y IGRP y EIGRP, OSPF.
# Este enrutamiento posee una gran convergencia y escala mucho mejor que el de redes, but tiene un alto costo
# en la utilizacion de recursos como son la ram, ciclo de CPU, y ancho de banda. 

# Los protocolos de enturamiento indican al enrutador como enrutarse. mientras que los protocolos enrutados
# son aquellos que están siendo enrutados por los protocolos de enturamiento.

# TAREA: 
# 	traer para que sirven los protocolos de enrutamiento
# 	RIP
# 	IGRP
# 	EIGRP

# que son sistemas autonomos en redes

app_proyecto/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.views.generic.list import ListView

from django.http import HttpResponse
from django.core import serializers
import json

from app_proyecto import models
# Create your views here.

def login(request):

	#SE EJECUTARÁ ESTA ACCION SI SE ACCEDE A LA PAGINA DEL MODO POST
	if request.method == "POST":
		#Obtiene los elementos de la base de datos
		datos = models.Empleado.objects.get(Curp=request.POST.get('f_curp'))
		if datos.contraseña == request.POST.get('f_contraseña'):

			#SE CREAN VARIABLES DE SESION
			request.session['curp'] = str(datos.Curp)
			request.session['id_puesto'] = str(datos.Id_Puesto)
	
			if str(datos.Id_Puesto) == "Empleado":
				return redirect('inicio_gerente')
			elif str(datos.Id_Puesto == "Supervisor"):
				return redirect('inicio_gerente')
			elif str(datos.Id_Puesto == "Gerente"):
				return redirect('inicio_gerente')
	
	#EL USUARIO TIPEÓ LA URL
	else:
		return render(request, 'app_proyecto/login.html')


def logout(request):
    #SE DESTRUYEN LAS VARIABLES DE SESION
    try:
        del request.session['curp']
        del request.session['id_puesto']
    except KeyError:
        pass
	#DESPUES DE DESTRUIR LAS VARIABLES DE SESIÓN, TE REDIGIRÁ A LA URL QUE TENGA EL NOMBRE "login"
    return redirect('login')

# ENLACES DEL GERENTE!
def inicio_gerente(request):
	return render(request, 'app_proyecto/gerente/index.html')

class consulta_empleados(ListView):
    template_name= "app_proyecto/gerente/consulta_empleados.html"
    queryset = models.Empleado.objects.filter(Id_Puesto = 0)

class consulta_supervisores(ListView):
    template_name= "app_proyecto/gerente/consulta_supervisores.html"
    queryset = models.Empleado.objects.filter(Id_Puesto = 1)

class consulta_gerentes(ListView):
    template_name= "app_proyecto/gerente/consulta_gerentes.html"
    queryset = models.Empleado.objects.filter(Id_Puesto = 2)

#FORMULARIOS OBLIGATORIOS
class form_persona(CreateView):
    template_name= "app_proyecto/form_persona.html"
    model = models.Personas
    fields = "__all__"
    success_url = reverse_lazy("login")

class form_persona_domicilio(CreateView):
    template_name= "app_proyecto/form_persona_domicilio.html"
    model = models.DireccionPersonas
    fields = "__all__"
    success_url = reverse_lazy("login")

def json_supervisor(request):
	data = serializers.serialize('json', models.Empleado.objects.filter(Id_Puesto = 2))
	return HttpResponse(data, "application/json")


#----------------- EXAMENES -----------------
def examen_jefe_abarrotes(request):	
	#SE EJECUTARÁ ESTA ACCION SI SE ACCEDE A LA PAGINA DEL MODO POST
	if request.method == "POST":
		curp = str(request.POST.get('curp'))
		datos = models.Personas.objects.get(Curp = curp)

		# 1. Verifica si el curp ingresado existe en la bd
		if datos.Curp == curp:
			detalle_examen = models.Examen.objects.get(Id_Examen="Examen Jefe Abarrotes") #Obtiene los detalles del examen

			id_examen = detalle_examen.Id_Examen
			minimo = int(detalle_examen.puntaje_minimo)
			maximo = int(detalle_examen.puntaje_maximo)

			#Cacha los valores que trae el formulario
			puntaje_edad = int(request.POST.get('edad'))
			puntaje_ingles = int(request.POST.get('ingles'))
			puntaje_estudios = int(request.POST.get('estudios'))		
			arr_consultas = request.POST.getlist('consultas') #Lista de valores seleccionados
			arr_experiencia = request.POST.getlist('experiencia') #Lista de valores seleccionados
			arr_conocimientos = request.POST.getlist('conocimientos') #Lista de valores seleccionados

			puntale_consulta = 0
			puntale_experiencia = 0
			puntale_conocimiento = 0

			for puntaje in arr_consultas:
				puntale_consulta = puntale_consulta + int(puntaje)

			for puntaje in arr_experiencia:
				puntale_experiencia = puntale_experiencia + int(puntaje)

			for puntaje in arr_conocimientos:
				puntale_conocimiento = puntale_conocimiento + int(puntaje)
			
			resultado_examen = puntaje_edad + puntaje_ingles + puntaje_estudios + puntale_consulta + puntale_experiencia + puntale_conocimiento

			#1. Guardando el examenrealizado 
			p = models.ExamenPersonas(Curp=models.Personas.objects.get(Curp=curp), Id_Examen=models.Examen.objects.get(Id_Examen=id_examen))
			p.save()

			#2. Extraer "num_examen"
			detalle = models.ExamenPersonas.objects.get(Curp=curp, Id_Examen="Examen Jefe Abarrotes")
			num_examen = detalle.Num_Examen

			if resultado_examen >= minimo:
				p = models.ResultadoExamenes(Num_Examen=models.ExamenPersonas.objects.get(Num_Examen=num_examen), Puntaje=resultado_examen, Dictamen = "Aceptado")
				p.save()

				e = models.Empleado(Curp=models.Personas.objects.get(Curp=curp), Id_Puesto=models.PuestoEmpleado.objects.get(Id_Puesto="Jefe de abarrotes"))
				e.save()

				contexto = {'resultado':"Aceptado", "r_color": "green"}
				return render(request, "app_proyecto/examenes/examen_jefe_abarrotes.html", contexto)
			else:
				p = models.ResultadoExamenes(Num_Examen=models.ExamenPersonas.objects.get(Num_Examen=num_examen), Puntaje=resultado_examen, Dictamen = "Rechazado")
				p.save()
				contexto = {'resultado':"Suerte para la próxima bro :V", "r_color": "red"}
				return render(request, "app_proyecto/examenes/examen_jefe_abarrotes.html", contexto)		
		else:
			contexto = {'Sumatoria':'ERROR'}
			return render(request, "app_proyecto/examenes/examen_jefe_abarrotes.html", contexto)
	else:
		supervisor = models.Empleado.objects.get(Id_Puesto = "Supervisor")
		contexto = {"No_Empleado": supervisor.No_Empleado, "Contraseña": supervisor.contraseña}
		return render(request, "app_proyecto/examenes/examen_jefe_abarrotes.html", contexto)

def examen_cajas(request):	
	#SE EJECUTARÁ ESTA ACCION SI SE ACCEDE A LA PAGINA DEL MODO POST
	if request.method == "POST":
		curp = str(request.POST.get('curp'))
		datos = models.Personas.objects.get(Curp = curp)

		# 1. Verifica si el curp ingresado existe en la bd
		if datos.Curp == curp:
			detalle_examen = models.Examen.objects.get(Id_Examen="Examen Jefe de Cajas") #Obtiene los detalles del examen

			id_examen = detalle_examen.Id_Examen
			minimo = int(detalle_examen.puntaje_minimo)
			maximo = int(detalle_examen.puntaje_maximo)

			#Cacha los valores que trae el formulario
			puntaje_edad = int(request.POST.get('edad'))
			puntaje_ingles = int(request.POST.get('ingles'))
			puntaje_estudios = int(request.POST.get('estudios'))		
			arr_consultas = request.POST.getlist('consultas') #Lista de valores seleccionados
			arr_experiencia = request.POST.getlist('experiencia') #Lista de valores seleccionados

			puntale_consulta = 0
			puntale_experiencia = 0

			for puntaje in arr_consultas:
				puntale_consulta = puntale_consulta + int(puntaje)

			for puntaje in arr_experiencia:
				puntale_experiencia = puntale_experiencia + int(puntaje)

		
			resultado_examen = puntaje_edad + puntaje_ingles + puntaje_estudios + puntale_consulta + puntale_experiencia

			#1. Guardando el examenrealizado 
			p = models.ExamenPersonas(Curp=models.Personas.objects.get(Curp=curp), Id_Examen=models.Examen.objects.get(Id_Examen=id_examen))
			p.save()

			#2. Extraer "num_examen"
			detalle = models.ExamenPersonas.objects.get(Curp=curp, Id_Examen="Examen Jefe de Cajas")
			num_examen = detalle.Num_Examen

			if resultado_examen >= minimo:
				p = models.ResultadoExamenes(Num_Examen=models.ExamenPersonas.objects.get(Num_Examen=num_examen), Puntaje=resultado_examen, Dictamen = "Aceptado")
				p.save()

				e = models.Empleado(Curp=models.Personas.objects.get(Curp=curp), Id_Puesto=models.PuestoEmpleado.objects.get(Id_Puesto="Jefe de Cajas"))
				e.save()

				contexto = {'resultado':"Aceptado", "r_color": "green"}
				return render(request, "app_proyecto/login.html", contexto)
			else:
				p = models.ResultadoExamenes(Num_Examen=models.ExamenPersonas.objects.get(Num_Examen=num_examen), Puntaje=resultado_examen, Dictamen = "Rechazado")
				p.save()
				contexto = {'resultado':"Suerte para la próxima bro :V", "r_color": "red"}
				return render(request, "app_proyecto/examenes/login.html", contexto)		
		else:
			contexto = {'Sumatoria':'ERROR'}
			return render(request, "app_proyecto/examenes/examen_cajas.html", contexto)
	else:
		supervisor = models.Empleado.objects.get(Id_Puesto = "Supervisor")
		contexto = {"No_Empleado": supervisor.No_Empleado, "Contraseña": supervisor.contraseña}
		return render(request, "app_proyecto/examenes/examen_cajas.html", contexto)

templates/app_proyecto/base.html
{% load static %}
{%block condiciones%}
{%if request.session.id_puesto  == "Gerente"%}
		<script>window.location.replace("../inicio_gerente");</script>
	{%elif request.session.id_puesto  == "Supervisor"%}
		<script>alert("Es Supervisor")</script>
	{%elif request.session.id_puesto  == "Empleado"%}
		<script>alert("Es Empleado")</script>
{%endif%}
{% endblock %}
<!DOCTYPE html>
<html lang="es">
<head>
	<title>{% block titulo %}Archivo base{% endblock %}	</title>
	{% block estilos %}
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'app_proyecto/fontawesome/css/fontawesome-all.css' %}" />

	<link rel="stylesheet" type="text/css" href="{% static 'app_proyecto/materialize/css/materialize.min.css' %}" />

	<link rel="stylesheet" type="text/css" href="{% static 'app_proyecto/style_presonalizada.css' %}" />
	<script src="{% static 'app_proyecto/jquery-3.2.1.min.js' %}"></script>

	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	{% endblock %}	
</head>
<body>
	{% block nav_dropdowns %}
	 <ul id="drop_solicitud_empleado" class="dropdown-content">
        <li><a href="../form_persona">Datos Personales</a></li>
        <li><a href="../form_persona_domicilio">Domicilio</a></li>
     </ul>
     <ul id="drop_examenes_puestos" class="dropdown-content">
        <li><a href="../examen_cajas">Caja</a></li>
        <li><a href="../examen_jefe_abarrotes">Jefe de Abarrotes</a></li>
     </ul>
	{% endblock %}	
	{% block navbar %}
		<nav class="teal darken-4">
			<div class="nav-wrapper">
				<a class="brand-logo center">{% block titulo_navbar %}Archivo base{% endblock %}</a>
				{% block nav_contenido %}
				  <ul>
				  	<li><a href="../login">Inicio</a></li>
					<li><a class="dropdown-button" href="#!" data-activates="drop_solicitud_empleado"><i class="fas fa-chevron-circle-down fa-1x"></i>  Mi Registro</a></li>
					<li><a class="dropdown-button" href="#!" data-activates="drop_examenes_puestos"><i class="fas fa-chevron-circle-down fa-1x"></i>  Pruebas</a></li>
				  </ul>
				{% endblock %}				
			</div>
		</nav>
	{% endblock %}

	{% block contenido %}
	{% endblock %}	

	{% block mas_contenido %}

	{% endblock %}	

	{% block pie_pagina %}
		<footer class="teal darken-4">
			<div class="footer-copyright">
				<div class="container center">
					© 2018 Todos los derechos reservados 
				</div>
			</div>
		</footer>
	{% endblock %}	
	{% block javascrip %}
	<script src="{% static 'app_proyecto/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'app_proyecto/materialize/js/materialize.min.js' %}"></script>
	<script>
		  $(document).ready(function() {
	     	// Initialize collapse button
  			$(".button-collapse").sideNav();
		  });     

		$(document).ready(function() {
		$('select').material_select();
		}); 
	</script>
	{% endblock %}	
</body>
</html>

templates/app_proyecto/form_caja.html
{% extends 'app_proyecto/base.html' %}

{% block titulo %}Caja{% endblock %} 

{% block titulo_navbar %}caja{% endblock %}

{% block contenido %}

<div class="container" style="width: 50%;">
	<form method="post" >
	    {% csrf_token %}	 

<div class="input-field col s12">
	<select multiple>
	    <option value="" disabled selected> 1.-Nivel de estudios </option>
	    <option value="1">Secundaria</option>
	    <option value="2">Preparatoria</option>
	    <option value="3">Superior</option>
	</select>
</div>
	<label> 1.-Nivel de estudios: </label>
	<select class="browser-default">
		<option value="" disabled selected>Seleccione una opción</option>
	    <option value="1">Secundaria</option>
	    <option value="2">Preparatoria</option>
	    <option value="3">Superior</option>
	</select>



<div class="input-field col s12">
	<select multiple>
		<option value="" disabled selected> 2.-Conocimientos concretos aplicado: </option>   
		<option value="1">Solución de problemas</option>
		<option value="2">Operaciones básicas para atender eventualidades en cajas</option>
	    <option value="3">Aplicaciones básicas psicológicas para dirigirse al cliente</option>
		<option value="4">Atención y soluciones para el cliente</option>
	</select>
</div>
	<label> 2.-Conocimientos concretos aplicado: </label>
	<select class="browser-default">   
		<option value="" disabled selected>Seleccione una opción</option>
    	<option value="1">Solución de problemas</option>
    	<option value="2">Operaciones básicas para atender eventualidades en cajas</option>
    	<option value="3">Aplicaciones básicas psicológicas para dirigirse al cliente</option>
     	<option value="4">Atención y soluciones para el cliente</option>
	</select>


<div class="input-field col s12">
	<select multiple>
		<option value="" disabled selected> 3.-Conocimiento de ingles: </option>   
	    <option value="1">Básico</option>
	    <option value="2">Intermedio</option>
	    <option value="3">Avanzado</option>
   		<option value="4">Nada</option>
	</select>
</div>
	<label>3.-Conocimiento de ingles: </label>
  	<select class="browser-default">
  		<option value="" disabled selected>Seleccione una opción</option>
    	<option value="1">Básico</option>
    	<option value="2">Intermedio</option>
    	<option value="3">Avanzado</option>
   		<option value="4">Nada</option>
	</select>



<div class="input-field col s12">
	<select multiple>
		<option value="" disabled selected> 4.-Experiencia en puesto similares: </option>   
		<option value="1">Auxiliar especializado en cajas</option>
    	<option value="2">Auxiliar </option>
    	<option value="3">Subjefe en cajas</option>
   		<option value="4">Sin experiencia</option>
	</select>
</div>
	<label> 4.-Experiencia en puesto similares: </label>
  	<select class="browser-default">   
  		<option value="" disabled selected>Seleccione una opción</option>
    	<option value="1">Auxiliar especializado en cajas</option>
    	<option value="2">Auxiliar </option>
    	<option value="3">Subjefe en cajas</option>
   		<option value="4">Sin experiencia</option>
	</select>

<div class="input-field col s12">
	<select multiple>
 		<option value="" disabled selected> 5.-Conocimientos prácticos: </option>   
    	<option value="1">Control de personal</option>
    	<option value="2">Constante apego a políticas </option>
    	<option value="3">Estrategia en distribución del personal según la carga de trabajo </option>
   		<option value="4">Facilidad de palabra ante situaciones con el cliente.</option>
	</select>
</div>
	<label> 5.-Conocimientos prácticos: </label>
  	<select class="browser-default">   
  		<option value="" disabled selected>Seleccione una opción</option>
    	<option value="1">Control de personal</option>
    	<option value="2">Constante apego a políticas </option>
    	<option value="3">Estrategia en distribución del personal según la carga de trabajo </option>
   		<option value="4">Facilidad de palabra ante situaciones con el cliente.</option>
	</select>

<div class="input-field col s12">
	<select multiple>
	    <option value="" disabled selected> 6.-Edad  </option>
	    <option value="1">21 a 30</option>
	    <option value="2">31 a 40</option>
	    <option value="3">41 a 50</option>
	</select>
</div>
	<label> 6.-Edad: </label>
	<select class="browser-default">
		<option value="" disabled selected>Seleccione una opción</option>
	    <option value="1">21 a 30</option>
	    <option value="2">31 a 40</option>
	    <option value="3">41 a 50</option>
	</select>

		<div class="right">
			<button class="btn waves-effect teal darken-4" type="submit">Enviar
			  	<i class="fas fa-sign-in-alt left"></i>
			 </button>
		</div>
	</form>
</div>
{% endblock %}

templates/app_proyecto/form_persona.html
{% extends 'app_proyecto/base.html' %}

{% block titulo %}Registro{% endblock %} 

{% block titulo_navbar %}Registro{% endblock %}

{% block contenido %}
	<div class="container" style="width: 50%;">
	<form method="post">
	    {% csrf_token %}
	    <div class="input-field col s12">
	          <i class="fas fa-key prefix"></i>
	          <input id="icon_prefix" type="text" class="validate" maxlength="20" name="Curp" required="true" autocomplete="off">
	          <label for="icon_prefix">Curp</label>
        </div>

		 <div class="row">
			<div class="input-field col s4">
			  <i class="fas fa-address-card prefix"></i>

			  <input id="icon_prefix" type="text" class="validate" maxlength="150" name="Nombres" required="true" autocomplete="off">
			  
			  <label for="icon_prefix">Nombre</label>
			</div>
			<div class="input-field col s4">
			  <i class="fas fa-address-card prefix"></i>

			  <input id="icon_prefix" type="text" class="validate" maxlength="150" name="Ap_Paterno" required="true" autocomplete="off">
			  
			  <label for="icon_prefix">Apellido Paterno</label>
			</div>

			<div class="input-field col s4">
			  <i class="fas fa-address-card prefix"></i>

			  <input id="icon_prefix" type="text" class="validate" name="Ap_Materno" maxlength="100" required="true" autocomplete="off">
			  
			  <label for="icon_prefix">Apellido Materno</label>
			</div>
		
			<div class="input-field col s6">
			  <i class="fas fa-address-card prefix"></i>

			  <input id="icon_prefix" type="text" class="validate" name="NSS" maxlength="100" required="true" autocomplete="off">
			  
			  <label for="icon_prefix">Número de seguro social</label>
			</div>

			<div class="input-field col s6">
			  <i class="fas fa-address-card prefix"></i>

			  <input id="icon_prefix" type="text" class="validate" name="RFC" maxlength="40" required="true" autocomplete="off">
			  
			  <label for="icon_prefix">RFC</label>
			</div>
		</div>
         <div class="input-field col s12">
	          <i class="fas fa-birthday-cake prefix"></i>

	          <input id="icon_prefix" type="date" class="validate" name="Fecha_Nacimiento" maxlength="40" required="true" autocomplete="off">
	          
	          <label for="icon_prefix"></label>
        </div>
        <div class="row">
        	<div class="col s6">
        		<select name="estado_civil" required="" id="id_estado_civil">
				  <option value="" selected="">Estado Civil</option>
				  <option value="Casado">Casado</option>
				  <option value="Soltero">Soltero</option>
				  <option value="Divorciado">Divorciado</option>
				  <option value="Viudo">Viudo</option>
				  <option value="Comprometido">Comprometido</option>
				</select>
        	</div>
        	<div class="col s6">
        		<select name="nivel_escolar" required="" id="id_nivel_escolar">
				  <option value="" selected="">Escolaridad</option>

				  <option value="Primaria">Primaria</option>

				  <option value="Secundaria">Secundaria</option>

				  <option value="Preparatoria">Preparatoria</option>

				  <option value="Universidad">Universidad</option>
				</select>
        	</div>
        </div>
		<div class="right">
			<button class="btn waves-effect teal darken-4" type="submit">Enviar
		  	<i class="fas fa-sign-in-alt left"></i>
		  </button>
		</div>
	</form>
	<br>
	</div>
{% endblock %}

templates/app_proyecto/inicio.html
{% extends 'app_proyecto/base.html' %}
{% block titulo %}Iniciar sesión{% endblock %} 

{% block titulo_navbar %}Iniciar sesión{% endblock %}

{% block contenido %}
	<div class="container" style="width: 50%;">
		 <div class="row">
		    <form method="POST" class="col s12">
	    	{% csrf_token %}
		      <div class="row">
			        <div class="input-field col s12">
			          <i class="fas fa-user-circle prefix"></i>
			          <input id="icon_prefix" type="text" class="validate" name="username" required="true" autocomplete="off">
			          <label for="icon_prefix">Usuario</label>
			        </div>
			        <div class="input-field col s12">
			          <i class="fas fa-key prefix"></i>
			          <input id="icon_telephone" type="password" class="validate" name = "password" required="true" autocomplete="off">
			          <label for="icon_telephone">Contraseña</label>
			        </div>
		      	</div>
				<div class="right">
					<button class="btn waves-effect teal darken-4" type="submit">Iniciar
				  	<i class="fas fa-sign-in-alt left"></i>
				  </button>
				</div>
		    </form>
		</div>
	</div>
{% endblock %}